
name: Update Delivery Codes

on:
  schedule:
    - cron: '0 0 * * *'  # 每天執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  update-codes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 jinja2
        
    - name: Run script
      run: python scrape_delivery_codes.py
      
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
    - name: Pull latest changes
      run: |
        git pull origin main --allow-unrelated-histories
        
    - name: Commit and push if changed
      run: |
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update delivery codes" && git push)

```